window.ISCIZ_DATA = {
  currentUser: { name: "Stevey McVideo", role: "Admin", initials: "SM" },
  clients: [
    { code: "ADID", name: "Adidas",      active: true, createdAt: "2024-02-19" },
    { code: "APPL", name: "Apple",       active: true, createdAt: "2024-03-04" },
    { code: "TLSA", name: "Tesla",       active: true, createdAt: "2024-02-24" },
    { code: "TOYT", name: "Toyota",      active: true, createdAt: "2024-04-11" },
    { code: "NIKE", name: "Nike",        active: true, createdAt: "2024-03-22" },
    { code: "BMWW", name: "BMW",         active: true, createdAt: "2024-02-14" },
    { code: "FORD", name: "Ford",        active: true, createdAt: "2024-02-09" },
    { code: "PEPS", name: "PepsiCo",     active: true, createdAt: "2024-02-04" },
    { code: "MCDO", name: "McDonald's",  active: true, createdAt: "2024-01-31" },
    { code: "STBK", name: "Starbucks",   active: true, createdAt: "2024-01-19" },
    { code: "NFLX", name: "Netflix",     active: true, createdAt: "2024-01-14" },
    { code: "SRHC", name: "Searhc",      active: false, createdAt: "2026-01-23" },
  ],
  agencies: [
    { name: "R&R Partners",    default: true,  active: true, createdAt: "2023-11-02" },
    { name: "Wieden+Kennedy",  default: false, active: true, createdAt: "2024-01-18" },
    { name: "72andSunny",      default: false, active: true, createdAt: "2024-03-04" },
    { name: "Deutsch LA",      default: false, active: true, createdAt: "2024-04-22" },
    { name: "Droga5",          default: false, active: false,createdAt: "2024-06-11" },
  ],
  users: [
    { name:"Stevey McVideo", email:"stevey@rrpartners.com",  role:"Admin",  active:true,  createdAt:"2023-10-12" },
    { name:"Marco Silva",    email:"marco@rrpartners.com",   role:"Editor", active:true,  createdAt:"2023-11-04" },
    { name:"Jess Kwan",      email:"jess@rrpartners.com",    role:"Editor", active:true,  createdAt:"2024-01-22" },
    { name:"Priya Shah",     email:"priya@rrpartners.com",   role:"Editor", active:true,  createdAt:"2024-02-14" },
    { name:"Dana Lee",       email:"dana@rrpartners.com",    role:"Editor", active:true,  createdAt:"2024-05-30" },
    { name:"Alex Rivera",    email:"alex@rrpartners.com",    role:"Admin",  active:true,  createdAt:"2024-07-18" },
    { name:"Sam Patel",      email:"sam@rrpartners.com",     role:"Editor", active:false, createdAt:"2024-09-01" },
  ],
  isciCodes: [
    { code:"ADID2601", client:"Adidas", clientCode:"ADID", campaign:"Originals SS26", jobNumber:"123123", title:"ADID_OriginalsSS26_15s_Digital", length:15, placement:"Digital", aspectRatio:"16:9", fileFormat:"ProRes", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2026-01-30", createdBy:"Stevey McVideo", createdAt:"2026-01-27", description:"Hero spot for Spring/Summer Originals launch." },
    { code:"APPL2504", client:"Apple", clientCode:"APPL", campaign:"Innovations", jobNumber:"A-4402", title:"APPL_Innovation_6s_Digital", length:6, placement:"Digital", aspectRatio:"9:16", fileFormat:"ProRes", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2024-05-28", createdBy:"Jess Kwan", createdAt:"2024-05-22", description:"Vertical cutdown for social pre-roll." },
    { code:"TLSA2501", client:"Tesla", clientCode:"TLSA", campaign:"Autopilot", jobNumber:"TSL-12", title:"TLSA_Autopilot_30s_CTV", length:30, placement:"CTV", aspectRatio:"16:9", fileFormat:"ProRes", audio:"5.1 Surround", accessibility:"Clean", language:"English", market:"National", airDate:"2025-08-03", createdBy:"Marco Silva", createdAt:"2025-07-14", description:"Premium CTV spot highlighting new Autopilot features." },
    { code:"TOYT2505", client:"Toyota", clientCode:"TOYT", campaign:"Camry", jobNumber:"TC-509", title:"TOYT_Camry_45s_OLV", length:45, placement:"OLV", aspectRatio:"16:9", fileFormat:"H.264", audio:"Stereo LR", accessibility:"CC", language:"English", market:"National", airDate:"2024-12-01", createdBy:"Priya Shah", createdAt:"2024-11-10", description:"Longform online video spot, dealer tag included." },
    { code:"NIKE2503", client:"Nike", clientCode:"NIKE", campaign:"Just Do It", jobNumber:"N-8830", title:"NIKE_JustDoIt_6s_Social", length:6, placement:"Social", aspectRatio:"1:1", fileFormat:"H.264", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2024-09-23", createdBy:"Stevey McVideo", createdAt:"2024-09-18", description:"Square social bumper, IG feed." },
    { code:"NIKE2504", client:"Nike", clientCode:"NIKE", campaign:"Just Do It", jobNumber:"N-8830", title:"NIKE_JustDoIt_15s_Social", length:15, placement:"Social", aspectRatio:"9:16", fileFormat:"H.264", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2024-09-25", createdBy:"Stevey McVideo", createdAt:"2024-09-18", description:"Vertical social cutdown." },
    { code:"APPL2505", client:"Apple", clientCode:"APPL", campaign:"Innovations", jobNumber:"A-4402", title:"APPL_Innovation_15s_Digital", length:15, placement:"Digital", aspectRatio:"16:9", fileFormat:"ProRes", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2024-06-01", createdBy:"Jess Kwan", createdAt:"2024-05-22", description:"Digital cutdown, 15s." },
    { code:"BMWW2601", client:"BMW", clientCode:"BMWW", campaign:"i5 Launch", jobNumber:"B-77", title:"BMWW_i5Launch_30s_Broadcast", length:30, placement:"Broadcast", aspectRatio:"16:9", fileFormat:"ProRes", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2026-02-14", createdBy:"Marco Silva", createdAt:"2026-01-30", description:"Broadcast hero for i5 sedan launch." },
    { code:"FORD2512", client:"Ford", clientCode:"FORD", campaign:"F-150 Lightning", jobNumber:"F-2211", title:"FORD_F150Lightning_60s_Broadcast", length:60, placement:"Broadcast", aspectRatio:"16:9", fileFormat:"ProRes", audio:"5.1 Surround", accessibility:"CC", language:"English", market:"National", airDate:"2025-11-18", createdBy:"Priya Shah", createdAt:"2025-11-02", description:"Longform launch spot, includes dealer tag." },
    { code:"MCDO2508", client:"McDonald's", clientCode:"MCDO", campaign:"McValue", jobNumber:"M-331", title:"MCDO_McValue_15s_Broadcast", length:15, placement:"Broadcast", aspectRatio:"16:9", fileFormat:"ProRes", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2025-10-03", createdBy:"Jess Kwan", createdAt:"2025-09-20", description:"Value menu broadcast spot." },
    { code:"STBK2515", client:"Starbucks", clientCode:"STBK", campaign:"Fall Flavors", jobNumber:"S-114", title:"STBK_FallFlavors_15s_Social", length:15, placement:"Social", aspectRatio:"1:1", fileFormat:"H.264", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2025-08-29", createdBy:"Stevey McVideo", createdAt:"2025-08-15", description:"PSL seasonal social spot." },
    { code:"NFLX2520", client:"Netflix", clientCode:"NFLX", campaign:"Stranger Things 5", jobNumber:"N-ST5", title:"NFLX_StrangerThings5_30s_CTV", length:30, placement:"CTV", aspectRatio:"16:9", fileFormat:"ProRes", audio:"5.1 Surround", accessibility:"CC", language:"English", market:"National", airDate:"2025-11-05", createdBy:"Marco Silva", createdAt:"2025-10-12", description:"Hero tune-in spot for ST5 premiere." },
    { code:"PEPS2509", client:"PepsiCo", clientCode:"PEPS", campaign:"Summer Refresh", jobNumber:"P-77", title:"PEPS_SummerRefresh_30s_Broadcast", length:30, placement:"Broadcast", aspectRatio:"16:9", fileFormat:"ProRes", audio:"Stereo LR", accessibility:"Clean", language:"English", market:"National", airDate:"2025-06-01", createdBy:"Priya Shah", createdAt:"2025-05-10", description:"Summer seasonal broadcast spot." },
  ],
  placements: ["Broadcast","Digital","CTV","OLV","Social","Cinema"],
  aspectRatios: ["16:9","9:16","1:1","4:5","2.39:1"],
  fileFormats: ["ProRes","H.264","H.265","DNxHD"],
  lengths: [6,10,15,20,30,45,60,90,120],
  audioOptions: ["Stereo LR","Mono","5.1 Surround","Dolby Atmos"],
  accessibilityOptions: ["Clean","CC","Open Captions","Audio Description"],
  editors: ["Marco Silva","Jess Kwan","Priya Shah","Stevey McVideo","Dana Lee"],
};
(function(){
  const e=["Marco Silva","Jess Kwan","Marco Silva","Priya Shah","Stevey McVideo","Stevey McVideo","Jess Kwan","Marco Silva","Priya Shah","Jess Kwan","Stevey McVideo","Marco Silva","Priya Shah"];
  window.ISCIZ_DATA.isciCodes.forEach((c,i)=>{c.assignedEditor=e[i]||"Marco Silva";});
})();
